### ISSUE TITLE
مشکل در انتخاب تاریخ

### ISSUE THREAD

**Issue by hoveiser** [tahajahangir/jdate#3]
با سلام و عرض خسته نباشید خدمت شما
در قسمت انتخاب تاریخ ( گوشه سمت راست ) اگر وقتی که صفحه لود می شود از آن استفاد کنید کار نمی کند
ولی زمانی که یکی از گزینه های بالا سمت راست (مثلا سه ماهه یا یک ماهه) را انتخاب کنیم و بعد از آن از گزینه مذکور استفاده کنیم مشکل برطرف می شود

با تشکر

**Comment by tahajahangir** [comment]
‫این repo صرفا مربوط به کلاس جاواسکریپت JDate است، و سازگاری آن با highcharts صرفا برای دمو ذکر شده است.
‫با احتمال زیاد، این مشکل مربوط به سازگاری highcharts است و شما می‌بایست مشکل را به صورت دقیق‌تر بررسی و در ریپوی highcharts گزارش دهید.
‫در صورتیکه مشکلی هم در این repo است، لطفا دقیق‌تر بفرمایید

با تشکر از توجه شما
