### ISSUE TITLE
اضافه کردن تاریخ شمسی برای framework7

### ISSUE THREAD

**Issue by nopardazco** [tahajahangir/jdate#5]
سلام 
من در حال کار روی framework7 هستم
به نشانی : http://framework7.io
می خواستم از این تابع برای شمسی سازی بخش calendar این فریمورک استفاده کنم. ولی موفق نشدم.
دوست عزیز امکان داره اینکارو شما انجام بدید. 
من حاظرم بابت پیشبرد این هم هزینه کنم.

**Comment by mer30hamid** [comment]
سلام، اگر به این نشانی مراجعه کنید:
https://github.com/framework7io/framework7/issues/1631

بنده گفتم که این مشکل رو حل کردم (مشکل کار نکردن اسکریپت آقای جهانگیر) ، ضمنا همونطور که ملاحظه می کنید، جناب @nolimits4web هم اعلام کردند که مشکل شروع هفته هم در نسخه جدید حل شده و مطلبش قدیمی هست و اون "اعلام اشکال" رو به حالت بسته در آوردند. بنده درخواست pull دادم به آقای جهانگیر ولی هنوز قبول نکردن ایشون، شما می تونید از فورک بنده در این آدرس استفاده کنید و نتیجه را ببینید:

https://github.com/mer30hamid/jdate/

یه نمونه هم درست کردم در این آدرس می تونید ببینید که مشکل کاملا برطرف شده:

https://jsfiddle.net/xfkx2nz0/16/

**Comment by nopardazco** [comment]
@mer30hamid 
ممنونم از شما حمید کرد عزیز.
واقعا عالی بود دقیقا مشکل من هم همین بود که شما برطرف کردید.
